# Generated by Django 5.2.5 on 2025-11-06 16:21

from decimal import Decimal

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_product_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Formato: 12345678-9', max_length=12, unique=True, validators=[accounts.models.validate_rut_chileno], verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nombre de Fantasía')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(default='Chile', max_length=100, verbose_name='País')),
                ('plazo_pago', models.PositiveIntegerField(default=30, help_text='Días para el pago', verbose_name='Plazo de Pago (días)')),
                ('moneda', models.CharField(choices=[('CLP', 'Peso Chileno (CLP)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)')], default='CLP', max_length=3, verbose_name='Moneda')),
                ('condiciones_pago', models.CharField(default='Contado', max_length=255, verbose_name='Condiciones de pago')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento (%)')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('contacto_principal_nombre', models.CharField(blank=True, max_length=120, verbose_name='Contacto principal')),
                ('contacto_principal_email', models.EmailField(blank=True, max_length=254, verbose_name='Email contacto')),
                ('contacto_principal_telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono contacto')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('es_preferente', models.BooleanField(default=False, verbose_name='Proveedor Preferente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='control_por_lote',
            field=models.BooleanField(default=False, verbose_name='Control por lote'),
        ),
        migrations.AddField(
            model_name='product',
            name='control_por_serie',
            field=models.BooleanField(default=False, verbose_name='Control por serie'),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_estandar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Estándar'),
        ),
        migrations.AddField(
            model_name='product',
            name='costo_promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Promedio'),
        ),
        migrations.AddField(
            model_name='product',
            name='es_perecible',
            field=models.BooleanField(default=False, verbose_name='Producto Perecible'),
        ),
        migrations.AddField(
            model_name='product',
            name='ean_upc',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='EAN/UPC'),
        ),
        migrations.AddField(
            model_name='product',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Porcentaje de IVA', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IVA (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='mes_vencimiento',
            field=models.PositiveIntegerField(blank=True, help_text='Mes del año (1-12)', null=True, verbose_name='Mes de Vencimiento'),
        ),
        migrations.AddField(
            model_name='product',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='product',
            name='punto_reorden',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Punto de Reorden'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_maximo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock Máximo'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_url',
            field=models.URLField(blank=True, verbose_name='URL de imagen'),
        ),
        migrations.AddField(
            model_name='product',
            name='ficha_tecnica_url',
            field=models.URLField(blank=True, verbose_name='Ficha técnica (URL)'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_compra',
            field=models.CharField(default='UN', max_length=10, verbose_name='Unidad de compra'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_venta',
            field=models.CharField(default='UN', max_length=10, verbose_name='Unidad de venta'),
        ),
        migrations.AddField(
            model_name='product',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Factor de conversión Compra/Venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Actual'),
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo')),
                ('lead_time', models.PositiveIntegerField(default=7, help_text='Tiempo de entrega en días', verbose_name='Lead Time (días)')),
                ('min_lote', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Lote mínimo')),
                ('descuento_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento (%)')),
                ('es_preferente', models.BooleanField(default=False, verbose_name='Proveedor Preferente para este Producto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='production.product', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='production.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto-Proveedor',
                'verbose_name_plural': 'Productos-Proveedores',
                'ordering': ['-es_preferente', 'proveedor__razon_social'],
                'unique_together': {('product', 'proveedor')},
            },
        ),
    ]
