# Generated by Django 5.2.5 on 2025-11-07 03:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_product_aprobado_por_product_creado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: BOD-CENTRAL', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('lote', models.CharField(blank=True, help_text='Número de lote', max_length=50, verbose_name='Lote')),
                ('serie', models.CharField(blank=True, help_text='Número de serie', max_length=50, verbose_name='Serie')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('doc_referencia', models.CharField(blank=True, help_text='OC-123 / FAC-456 / GUIA-789', max_length=100, verbose_name='Documento de Referencia')),
                ('observaciones', models.TextField(blank=True, help_text='Notas de operación, recibo, daño, etc.', verbose_name='Observaciones')),
                ('motivo', models.CharField(blank=True, help_text='Diferencia inventario, devolución cliente, etc.', max_length=255, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='production.bodega', verbose_name='Bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='production.product', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='production.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['-fecha'], name='mov_fecha_idx'), models.Index(fields=['producto', '-fecha'], name='mov_prod_fecha_idx'), models.Index(fields=['bodega', '-fecha'], name='mov_bod_fecha_idx')],
            },
        ),
    ]
