# Generated by Django 5.2.5 on 2025-11-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_bodega_movimientoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoproveedor',
            name='lead_time',
            field=models.PositiveIntegerField(default=7, help_text='Tiempo de entrega en días', verbose_name='Tiempo de Entrega (días)'),
        ),
    ]
