# Generated by Django 5.2.5 on 2025-11-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('employee', 'Empleado'), ('viewer', 'Visualizador'), ('cliente', 'Cliente')], default='employee', max_length=50, verbose_name='Rol'),
        ),
    ]
