# Generated by Django 5.2.5 on 2025-11-06 16:21

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('employee', 'Empleado'), ('viewer', 'Visualizador'), ('cliente', 'Cliente'), ('proveedor', 'Proveedor')], default='employee', max_length=50, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='ProveedorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Formato: 12345678-9', max_length=12, validators=[accounts.models.validate_rut_chileno], verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nombre de Fantasía')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Proveedor Usuario',
                'verbose_name_plural': 'Proveedores Usuarios',
                'ordering': ['razon_social'],
            },
        ),
    ]
