# Generated by Django 5.2.5 on 2025-11-27 21:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_must_change_password'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('PASSWORD_RESET', 'Resetear Contraseña'), ('PASSWORD_CHANGE', 'Cambiar Contraseña'), ('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar')], max_length=50, verbose_name='Acción')),
                ('modelo', models.CharField(help_text='Nombre del modelo afectado (ej: Product, User, Proveedor)', max_length=100, verbose_name='Modelo')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales del evento', verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente', verbose_name='User Agent')),
                ('cambios', models.JSONField(blank=True, help_text='Detalles de los cambios realizados (JSON)', null=True, verbose_name='Cambios')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado anterior del objeto (JSON)', null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado nuevo del objeto (JSON)', null=True, verbose_name='Datos Nuevos')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='audit_fecha_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='audit_usuario_fecha_idx'), models.Index(fields=['modelo', '-fecha_hora'], name='audit_modelo_fecha_idx'), models.Index(fields=['accion', '-fecha_hora'], name='audit_accion_fecha_idx')],
            },
        ),
    ]
